### ISSUE TITLE
2 Factor authentication loop

### ISSUE THREAD

**Issue by LarGibbonFacts** [Voyz/ibeam#99] opened 2022-09-11 04:46 UTC
How's it going Voyz, I hope you're doing well.

During startup, IBeam keeps trying to perform the 2 factor authentication, but then proceeds to... log me out?:

```
2022-09-11 04:22:15,654|I| Authentication process succeeded
2022-09-11 04:22:18,908|E| Gateway session active but not authenticated
2022-09-11 04:22:18,909|I| Logging out and restarting the Gateway
2022-09-11 04:22:19,072|I| Gateway logout successful
2022-09-11 04:22:19,265|I| Gateway session found but not authenticated, authenticating...
```
it would loop like this continuously. 

I run  `docker run --env IBEAM_ACCOUNT=***--env IBEAM_PASSWORD=***-` because for whatever reason I have an authentication error when using the env.list file. maybe i need to provide account number instead of account username? I tried both, and it didn't work out still.

As an aside, as it's probably clear, I'm a noob at web development/coding. Do you suggest any books, channels, or something to advance past the million of tutorials out there?

Also thank you for maintaining this awesome piece of software and responding to everyone's questions/troubles!

IBeam version: 0.4.3
Docker image or standalone: b3affe3e6204b90901c8c2301bc340a40565802a255b72d66393593145c5ba87
Python version (standalone users only): 3.9
OS: Windows 11

**Comment by Voyz** [comment] 2022-09-14 09:56
Hey hey @LarGibbonFacts thanks for checking out IBeam and for reporting your issue 😊 Also thanks for the kind words, appreciate it!

> During startup, IBeam keeps trying to perform the 2 factor authentication, but then proceeds to... log me out?:

Unfortunately, this is a problem that multiple users have observed, yet we don't know the cause of it. The conclusion so far has been that this is due to the authentication session being expired - potentially due to a conflicting login, potentially due to an error on IBKR side - we don't exactly know. You can read more about this is some older issues, such as: https://github.com/Voyz/ibeam/issues/7

I'd recommend you try to run the Gateway without IBeam and see if you get similar behaviour and/or contact IBKR regarding this problem. There have been suggestions to ensure IBeam gets restarted on a daily basis to minimise its occurrence.

> maybe i need to provide account number instead of account username?

Seeing that IBeam displays `Authentication process succeeded` I'd conclude that this isn't necessary. 

> As an aside, as it's probably clear, I'm a noob at web development/coding. Do you suggest any books, channels, or something to advance past the million of tutorials out there?

I greet you fellow noob, we're all noobs here 👍 I'd recommend "Algorithmic Trading & DMA" book to get a broad understanding of some of the lingo that's going on. https://www.amazon.com/Algorithmic-Trading-DMA-introduction-strategies/dp/0956399207 Join the algotrading subreddit and start reading the posts there. Build your own trading system just for fun to get an idea of what kind of problems you encounter in algotrading. Good luck! 😊

**Comment by LarGibbonFacts** [comment] 2022-10-30 04:17
Ah, it was just because the account wasn't funded lol.

**Comment by Voyz** [comment] 2022-11-16 15:37
Great, I'm going to close this issue as it seems to be solved. Feel free to reopen if you'd like to continue the discussion 👍 Thanks for participating!

**Closed by Voyz** 2022-11-16 15:37 UTC
Labels: bug
